ignore:
  - .github
  - api/v1alpha1/generated.pb.go
  - api/v1alpha1/zz_generated.deepcopy.go
  - config
  - controllers
  - docs
  - hack
  - kill
  - runner
  - runtimes
coverage:
  status:
    # we've found this not to be useful
    patch: off
    project:
      default:
        # allow test coverage to drop by 2%, assume that it's typically due to CI problems
        threshold: 2