# https://golangci-lint.run/usage/quick-start/
run:
  concurrency: 4
  timeout: 5m
linters:
  enable:
    - deadcode
    - errcheck
    - goimports
    - gci
    - gofumpt
    - gosimple
    - govet
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unparam
    - unused
    - varcheck
linters-settings:
  goimports:
    local-prefixes: github.com/argoproj-labs/argo-dataflow/
