apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  name: example
spec:
  processors:
    - name: a
      image: docker/whalesay:latest

    - name: b
      image: docker/whalesay:latest