apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  name: example
spec:
  input:
    kafka:
      url: kafka-0.broker.kafka.svc.cluster.local:9092
      topic: my-topic

  processors:
    - name: a
      input:
        http: { }
      image: argoproj/dataflow-cat:latest
      output:
        http: { }

  output:
    kafka:
      url: kafka-0.broker.kafka.svc.cluster.local:9092
      topic: your-topic
