apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  name: example
  annotations:
    dataflow.argoproj.io/description: "Example pipeline"
spec:
  nodes:
    - name: a
      sources:
        - kafka:
            url: kafka-0.broker.kafka.svc.cluster.local:9092
            topic: input-topic
      from:
        http: { }
      image: argoproj/dataflow-cat:latest
      to:
        http: { }
      sinks:
        - bus:
            subject: a-b

    - name: b
      sources:
        - bus:
            subject: a-b
      from:
        http: { }
      image: argoproj/dataflow-cat:latest
      replicas:
        value: 2
      to:
        http: { }
      sinks:
        - kafka:
            url: kafka-0.broker.kafka.svc.cluster.local:9092
            topic: output-topic
