apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stan
spec:
  template:
    spec:
      # stan depends on nats, and will go into CrashloopBackoff if that is not ready
      initContainers:
        - name: wait
          image: quay.io/argoproj/dataflow-runner:latest
          imagePullPolicy: IfNotPresent
          args:
            - sleep
            - 20s
  volumeClaimTemplates:
    - metadata:
        name: stan-sts-vol
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: "Filesystem"
        resources:
          requests:
            storage: 16Gi