apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This examples shows the built-in grouping.

      Group are written using expression syntax and must return a string.

      [Learn about expressions](../docs/EXPRESSIONS.md)
    dataflow.argoproj.io/name: Filter messages
  creationTimestamp: null
  name: group
spec:
  steps:
  - group:
      endOfGroup: string(msg) contains "excited"
      format: JSONStringArray
      key: 'string(msg) contains "2" ? "even" : "odd"'
      storage:
        name: groups
    name: main
    sinks:
    - stan:
        subject: odd-even
    sources:
    - kafka:
        topic: input-topic
    volumes:
    - emptyDir: {}
      name: groups
