apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This pipeline count the number of words in a document, not the number of count of each word as you might expect.

      It also shows an example of a pipelines terminates based on a single step's status.
    dataflow.argoproj.io/name: Word count
    dataflow.argoproj.io/timeout: 2m
  name: word-count
spec:
  steps:
  - container:
      args:
      - sh
      - -c
      - |
        cat /in/text | tee -a /var/run/argo-dataflow/out
      image: ubuntu:latest
      volumeMounts:
      - mountPath: /in
        name: in
    name: read-text
    sinks:
    - stan:
        subject: lines
    volumes:
    - configMap:
        name: word-count-input
      name: in
  - container:
      args:
      - bash
      - -c
      - |
        set -eux -o pipefail
        while read sentence; do
          for word in $sentence; do
              echo $word
          done
        done > /var/run/argo-dataflow/out < /var/run/argo-dataflow/in
      image: ubuntu:latest
      in:
        fifo: true
    name: split-lines
    replicas:
      max: 1
      min: 0
      ratio: 1
    sinks:
    - stan:
        subject: words
    sources:
    - stan:
        subject: lines
  - container:
      args:
      - bash
      - -c
      - |
        set -eux -o pipefail
        i=0
        while read word && [ $word != EOF ]; do
          i=$((i+1))
        done < /var/run/argo-dataflow/in
        echo $i > /var/run/argo-dataflow/out
      image: ubuntu:latest
      in:
        fifo: true
    name: count-words
    sinks:
    - kafka:
        topic: output-topic
    sources:
    - stan:
        subject: words
    terminator: true

---
apiVersion: v1
data:
  text: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    EOF
kind: ConfigMap
metadata:
  name: word-count-input
