apiVersion: v1
kind: Secret
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This is an example of providing a namespace named Kafka configuration.

      The secret must be named `dataflow-kafka-${name}`.

      [Learn about configuration](../docs/CONFIGURATION.md)
    dataflow.argoproj.io/name: Default Kafka config
  name: dataflow-kafka-default
stringData:
  url: kafka-0.broker:9092
