# permissions for end users to view funcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: func-viewer-role
rules:
- apiGroups:
  - dataflow.argoproj.io
  resources:
  - funcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataflow.argoproj.io
  resources:
  - funcs/status
  verbs:
  - get
