apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline
rules:
- apiGroups:
  - dataflow.argoproj.io
  resources:
  - steps/status
  verbs:
  - patch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
