# permissions for end users to edit replicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicaset-editor-role
rules:
- apiGroups:
  - dataflow.argoproj.io
  resources:
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataflow.argoproj.io
  resources:
  - replicasets/status
  verbs:
  - get
