apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: argo-server
          image: quay.io/argoproj/argocli:dev-dataflow
          imagePullPolicy: Always
          args: [ server, --secure=false, --namespaced=true, --auth-mode=server ]
          readinessProbe:
            httpGet:
              port: 2746
              scheme: HTTP

