resources:
  - github.com/argoproj/argo-workflows/manifests/base/argo-server?ref=stable
  - github.com/argoproj/argo-workflows/manifests/namespace-install/argo-server-rbac?ref=stable
  - argo-server-deployment.yaml
