apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  template:
    spec:
      # kafka depends on pzoo, and will go into CrashloopBackoff if it is not ready
      initContainers:
        - name: wait
          image: quay.io/argoproj/dataflow-runner:latest
          imagePullPolicy: IfNotPresent
          args:
            - sleep
            - 10s
