apiVersion: v1
kind: Service
metadata:
  name: default-nats
spec:
  selector:
    name: nats-streaming-operator
  ports:
    - name: client
      port: 4222
    - name: cluster
      port: 6222
    - name: monitor
      port: 8222