apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-ui
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nats-ui
  template:
    metadata:
      labels:
        app: nats-ui
    spec:
      containers:
        - name: main
          image: kuali/nats-streaming-console:latest
          env:
            - name: STAN_URL
              value: http://nats:4222
            - name: STAN_MONITOR_URL
              value: http://nats:8222
            - name: STAN_CLUSTER
              value: default
          ports:
            - containerPort: 8282