apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |-
      This example of Go 1.16 handler.

      [Learn about handlers](../docs/HANDLERS.md)
    dataflow.argoproj.io/owner: argoproj-labs
  name: 104-go1-16
spec:
  steps:
  - handler:
      code: |-
        package main

        func Handler(m []byte) ([]byte, error) {
          return []byte("hi " + string(m)), nil
        }
      runtime: go1-16
    name: main
    sinks:
    - log: {}
    sources:
    - kafka:
        topic: input-topic
