apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |-
      This example is of the Java 16 handler.

      [Learn about handlers](../docs/HANDLERS.md)
  name: java-16
spec:
  steps:
  - handler:
      code: |-
        public class Handler {
            public static byte[] Handle(byte[] msg) throws Exception {
                return msg;
            }
        }
      runtime: java16
    name: main
    sinks:
    - kafka:
        topic: output-topic
    sources:
    - kafka:
        topic: input-topic
