apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This example demostrates having a terminator step, and then terminating other steps
      using different terminations strategies.
    dataflow.argoproj.io/wait-for: Completed
  creationTimestamp: null
  name: terminator
spec:
  steps:
  - container:
      args:
      - sh
      - -c
      - |
        cat
      image: ubuntu:latest
    name: ubuntu
  - cat: {}
    name: runner
  - container:
      args:
      - sh
      - -c
      - |
        exit 0
      image: ubuntu:latest
    name: terminator
    terminator: true
