apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |-
      This example shows a pipeline running to completion.

      A pipeline that run to completion (aka "terminating") is one that will finish.

      For a pipeline to terminate one of two things must happen:

      * Every steps exits successfully (i.e. with exit code 0).
      * One step exits successfully, and is marked with `terminator: true`. When this happens, all other steps are killed.
    dataflow.argoproj.io/wait-for: Completed
  name: completion
spec:
  steps:
  - container:
      args:
      - sh
      - -c
      - exit 0
      image: ubuntu:latest
    name: main
