apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This example has two sinks
  creationTimestamp: null
  name: 301-two-sinks
spec:
  steps:
  - cat: {}
    name: main
    sinks:
    - log: {}
      name: a
    - log: {}
      name: b
    sources:
    - kafka:
        topic: input-topic
