apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This example uses parallel to 2x the amount of data it processes.
    dataflow.argoproj.io/name: Parallel
    dataflow.argoproj.io/test: "false"
  creationTimestamp: null
  name: parallel
spec:
  steps:
  - cat: {}
    name: main
    sinks:
    - log: {}
    sources:
    - kafka:
        parallel: 2
        topic: input-topic
