apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This example shows a pipelne running to completion.

      A pipeline that run to completion (aka "terimanting") is one that will finish
    dataflow.argoproj.io/name: Runs to completion
  creationTimestamp: null
  name: completion
spec:
  steps:
  - container:
      args:
      - sh
      - -c
      - |
        exit 0
      image: debian:10.7-slim
    name: main
