apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  name: fifo
  annotations:
    dataflow.argoproj.io/description: "Pipeline using FIFOs"
spec:
  nodes:
    - name: a
      sources:
        - kafka:
            url: kafka-0.broker.kafka.svc.cluster.local:9092
            topic: input-topic
      in:
        fifo: true
      image: debian:10.7-slim
      imagePullPolicy: IfNotPresent
      args:
        - sh
        - -c
        - |
          cat /var/run/argo-dataflow/in > /var/run/argo-dataflow/out
      out:
        fifo: true
      sinks:
        - kafka:
            url: kafka-0.broker.kafka.svc.cluster.local:9092
            topic: output-topic
