apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This example use named pipe to send and receive messages.

      Two named pipes are made available:

      The container can read lines from `/var/run/argo-dataflow/in`. Each line will be a single message.

      The contain can write to `/var/run/argo-dataflow/out`. Each line MUST be a single message.
      You MUST escape new lines.
    dataflow.argoproj.io/name: Using FIFOs for input and outputs
  creationTimestamp: null
  name: fifos
spec:
  funcs:
  - args:
    - sh
    - -c
    - |
      cat /var/run/argo-dataflow/in | while read line ; do
        echo "hello $line"
      done > /var/run/argo-dataflow/out
    image: debian:10.7-slim
    imagePullPolicy: IfNotPresent
    in:
      fifo: true
    name: main
    out:
      fifo: true
    resources: {}
    sinks:
    - kafka:
        topic: output-topic
    sources:
    - kafka:
        topic: input-topic
