apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  name: http
  annotations:
    dataflow.argoproj.io/description: "Pipeline using HTTP"
spec:
  nodes:
    - name: a
      sources:
        - kafka:
            url: kafka-0.broker.kafka.svc.cluster.local:9092
            topic: input-topic
      in:
        http: { }
      image: argoproj/dataflow-cat:latest
      imagePullPolicy: IfNotPresent
      out:
        http: { }
      sinks:
        - kafka:
            url: kafka-0.broker.kafka.svc.cluster.local:9092
            topic: output-topic
