apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This example shows a example of having two nodes in a pipeline.

      They are connected by a subject.

      By convention, subjects should be the two node names with a hyphen.

      If the first node is named `foo` and the second is named `bar`, then the subject should be `foo-bar`.

      Subjects names only need to be unique within the pipeline.
    dataflow.argoproj.io/name: Two nodes pipeline
  creationTimestamp: null
  name: two-node
spec:
  steps:
  - container:
      args:
      - cat
      image: argoproj/dataflow-runner:latest
    name: a
    sinks:
    - nats:
        subject: a-b
    sources:
    - kafka:
        topic: input-topic
  - container:
      args:
      - cat
      image: argoproj/dataflow-runner:latest
    name: b
    sinks:
    - kafka:
        topic: output-topic
    sources:
    - nats:
        subject: a-b
