apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This example shows a example of having two nodes in a pipeline.

      They are connected by a subject.

      By convention, subjects should be the two node names with a hyphen.

      If the first node is named `foo` and the second is named `bar`, then the subject should be `foo-bar`.

      Subjects names only need to be unique within the pipeline.
    dataflow.argoproj.io/name: Two nodes pipeline
  creationTimestamp: null
  name: two-node
spec:
  funcs:
  - args:
    - cat
    image: argoproj/dataflow-runner:latest
    imagePullPolicy: IfNotPresent
    in:
      http: {}
    name: a
    out:
      http: {}
    resources: {}
    sinks:
    - nats:
        subject: a-b
    sources:
    - kafka:
        topic: input-topic
  - args:
    - cat
    image: argoproj/dataflow-runner:latest
    imagePullPolicy: IfNotPresent
    in:
      http: {}
    name: b
    out:
      http: {}
    resources: {}
    sinks:
    - kafka:
        topic: output-topic
    sources:
    - nats:
        subject: a-b
