apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This pipeline processes pets (cats and dogs).
    dataflow.argoproj.io/name: Vetinary
  name: vet
spec:
  steps:
  - container:
      args:
      - sh
      - -c
      - |
        cat /in/text | tee -a /var/run/argo-dataflow/out
      image: debian:10.7-slim
      volumeMounts:
      - mountPath: /in
        name: in
      volumes:
      - configMap:
          name: pets
        name: in
    name: read-pets
    sinks:
    - stan:
        subject: animals
  - filter: string(msg) contains "cat"
    name: filter-cats
    sinks:
    - stan:
        subject: cats
    sources:
    - stan:
        subject: animals
  - map: json("Meow! " + object(msg).name)
    name: process-cats
    sinks:
    - kafka:
        topic: output-topic
    sources:
    - stan:
        subject: cats
  - filter: string(msg) contains "dog"
    name: filter-dogs
    sinks:
    - stan:
        subject: dogs
    sources:
    - stan:
        subject: animals
  - map: json("Woof! " + object(msg).name)
    name: process-dogs
    sinks:
    - kafka:
        topic: output-topic
    sources:
    - stan:
        subject: dogs

---
apiVersion: v1
data:
  text: |
    {"type": "dog", "name": "Emma"}
    {"type": "cat", "name": "Dino"}
    EOF
kind: ConfigMap
metadata:
  name: pets
