apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This pipeline count the number of words in a document, not the number of count of each word as you might expect.

      For that we need `GroupByKey`.

      It also shows an example of a pipelines where nodes run to completion.
    dataflow.argoproj.io/name: Word Count
  name: word-count
spec:
  funcs:
  - container:
      args:
      - sh
      - -c
      - |
        cat /in/text | tee -a /var/run/argo-dataflow/out
      image: debian:10.7-slim
      name: main
      out:
        fifo: true
      resources: {}
      volumeMounts:
      - mountPath: /in
        name: in
      volumes:
      - configMap:
          name: word-count-input
        name: in
    name: read-text
    sinks:
    - nats:
        subject: a-b
  - container:
      args:
      - sh
      - -c
      - |
        cat /var/run/argo-dataflow/in | while read sentence; do
          [ $sentence = EOF ] && exit 0
          for word in $sentence; do
              echo $word
          done
        done | tee -a /var/run/argo-dataflow/out
      image: debian:10.7-slim
      imagePullPolicy: IfNotPresent
      in:
        fifo: true
      name: main
      out:
        fifo: true
      resources: {}
    name: split-lines
    replicas:
      value: 5
    sinks:
    - nats:
        subject: b-c
    sources:
    - nats:
        subject: a-b
  - args:
    - sh
    - -c
    - |
      i=0
      cat /var/run/argo-dataflow/in | while read word; do
        if [ $word = EOF ]; then
            echo $i
            exit 0
        fi
        i=$((i+1))
      done | tee -a /var/run/argo-dataflow/out
    image: debian:10.7-slim
    in:
      fifo: true
    name: count-words
    out:
      fifo: true
    resources: {}
    sinks:
    - kafka:
        topic: output-topic
    sources:
    - nats:
        subject: b-c

---
apiVersion: v1
data:
  text: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    EOF
kind: ConfigMap
metadata:
  name: word-count-input
