apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stan
spec:
  template:
    spec:
      # stan depends on nats, and will go into CrashloopBackoff if nats is not ready
      initContainers:
        - name: wait
          image: quay.io/argoproj/dataflow-runner:latest
          args:
            - wait
            - 10s
