apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stan
spec:
  template:
    spec:
      # stan depends on nats, and will go into CrashloopBackoff if nats is not ready
      initContainers:
        - name: wait
          image: golang:1.16
          command:
            - sh
            - -c
          args:
            - |
              sleep 10s
