kind: Pod
apiVersion: v1
metadata:
  name: input
spec:
  containers:
    - name: main
      image: golang:1.16
      command:
        - sh
        - -c
      args:
        - |
          set -x
          while true; do
            go install github.com/argoproj-labs/argo-dataflow/hack/kafka@main
            kafka -topic input-topic create-topic
            kafka -topic output-topic create-topic
            # change sleep to 10ms to flood the topic
            kafka -topic input-topic -sleep 2s pump-topic
            sleep 5s
          done
