resources:
  - ../quick-start

patchesStrategicMerge:
  - controller-manager-deploy.yaml
  - argo-server-deploy.yaml

images:
  - name: alexcollinsintuit/dataflow-runner
    newName: argoproj/dataflow-runner

