kind: Pod
apiVersion: v1
metadata:
  name: input
spec:
  containers:
    - name: main
      image: golang:1.16
      command:
        - sh
        - -c
      args:
        - |
          set -eux
          git clone --depth 1 --single-branch https://github.com/alexec/argo-dataflow
          cd argo-dataflow
          until curl kafka-0.broker:9092 ; do sleep 10s ; done
          go run -v ./hack/kafka -topic input-topic create-topic
          go run -v ./hack/kafka -topic output-topic create-topic
          go run -v ./hack/kafka -topic input-topic pump-topic
