kind: Pod
apiVersion: v1
metadata:
  name: input
spec:
  containers:
    - name: main
      image: golang:1.16
      command:
        - sh
        - -c
      args:
        - |
          set -x
          git clone --depth 1 --single-branch https://github.com/argoproj-labs/argo-dataflow
          cd argo-dataflow/hack/kafka
          [ -e go.mod ] || go mod init github.com/argoproj-labs/argo-dataflow/hack/kafka
          while true; do
            go run -v . -topic input-topic create-topic
            go run -v . -topic output-topic create-topic
            # change sleep to 10ms to flood the topic
            go run -v . -topic input-topic -sleep 2s pump-topic
            sleep 5s
          done
