kind: Pod
apiVersion: v1
metadata:
  name: input
spec:
  containers:
    - name: main
      image: golang:1.16
      command:
        - sh
        - -c
      args:
        - |
          set -eux
          git clone --depth 1 --single-branch https://github.com/argoproj-labs/argo-dataflow
          cd argo-dataflow
          go run -v ./hack/kafka -topic input-topic create-topic
          go run -v ./hack/kafka -topic output-topic create-topic
          # change 1s to 10ms to flood the kafka topic
          go run -v ./hack/kafka -topic input-topic -sleep 1s pump-topic
