# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
name: Merge changelog updates
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: "${{ github.actor == 'github-actions[bot]' && github.event.pull_request.title == 'docs: updated CHANGELOG.md' }}"
    steps:
      - name: Merge PR
        run: gh pr merge --admin --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}