name: Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildx:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ cat, controller, init, sidecar ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build . --target ${{matrix.target}} --tag alexcollinsintuit/dataflow-${{matrix.target}}:latest
      - run: docker push alexcollinsintuit/dataflow-${{matrix.target}}:latest
