name: Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildx:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ controller, runner ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - run: docker build . --target ${{matrix.target}} --tag quay.io/argoproj/dataflow-${{matrix.target}}:latest
      - run: docker push quay.io/argoproj/dataflow-${{matrix.target}}:latest
