name: Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildx:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ cat, sidecar, controller ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # https://github.com/docker/setup-buildx-action#usage
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - run: docker build . --target ${{matrix.target}} --tag alexcollinsintuit/dataflow-${{matrix.target}}:latest
      - run: docker push alexcollinsintuit/dataflow-${{matrix.target}}:latest
