name: E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: actions-k3s
        uses: debianmaster/actions-k3s@v1.0.1
        with:
          version: v1.18.2-k3s1
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.2"
      - run: kubectl create sa default
      - run: make install
      - run: make deploy
      - run: make start
      - run: make wait
      - run: make test-examples