name: E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: actions-k3s
        uses: debianmaster/actions-k3s@v1.0.1
        with:
          version: v1.18.2-k3s1
      - run: kubectl create ns argo-dataflow-system
      - run: kubectl -n argo-dataflow-system create sa default
      - run: kubectl apply -k config/crd
      - run: kubectl apply -f config/quick-start.yaml