name: E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: actions-k3s
        uses: debianmaster/actions-k3s@v1.0.1
        with:
          version: v1.18.2-k3s1
      - run: kubectl apply -k config/crd
      - run: make deploy