name: E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: actions-k3s
        uses: debianmaster/actions-k3s@v1.0.1
        with:
          version: v1.18.2-k3s1
      - run: kubectl create sa default
      - run: make install
      - run: make deploy
      - run: make start 2>&1 /tmp/logs &
      - run: make wait
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.2"
      - run: make test-examples
      - name: Upload logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: /tmp/logs